### ISSUE TITLE
Avatar rendering during rotation

### ISSUE THREAD

**Issue by VirgiliaBeatrice** [zlguo1996/jitsi-party#10]
**Is your feature request related to a problem? Please describe.**
The current avatar's orientation will keep a same value during rotation.

**Describe the solution you'd like**
It's better to render the avatar as the desired orientation.

**Describe alternatives you've considered**
Showing a rotated name instead of video rendering might be an alternative solution.

**Comment by zlguo1996** [comment]
The reason current avatar not rotate is a consideration of performance: If rotate avater during user interaction, for every user rotate event, we have to update all participants.  

By the way, the problem could be solved if [Solution 1](https://github.com/zlguo1996/jitsi-party/issues/7#issuecomment-635248137) is applied in #7 .
