### ISSUE TITLE
Shape of stream avatar change from circule to square after map rotation

### ISSUE THREAD

**Issue by zlguo1996** [zlguo1996/jitsi-party#7]
Before rotate map:
![image](https://user-images.githubusercontent.com/17405914/82993821-2ce66500-a03c-11ea-9d2e-829b9a589ea6.png)
After rotate map:
![image](https://user-images.githubusercontent.com/17405914/82993857-3a035400-a03c-11ea-98ec-eb0dee6b4a58.png)

**Comment by zlguo1996** [comment]
The problem is caused by 2 nested rotate on CSS-transform. Border radius CSS would not work in that situation. 
The following shows video border radius would display correctly with counter rotation disabled (only one rotation):
![image](https://user-images.githubusercontent.com/17405914/82995235-50121400-a03e-11ea-8879-0f1f723ae3fa.png)

**Comment by zlguo1996** [comment]
**Solution 1**
One solution is does not render video inside Base component. Since video is not transform with map, no need to counter rotate video. As an alternative, we could render video inside another div, which is sibling to Base component. In this div, every video tag is positioned seperately.
The problem would be the isolation of background pointer SVG and video tag. When two participants are partially overlapped, the isolation might looks strange.
Another thing need to be tested is performance. Without transform CSS, rendering video might be faster. But update every single video tag seperately might have bad effect on performance.

**Comment by zlguo1996** [comment]
**Performance tests for solution 1**  

To test the performance of rendering positioned avatar with different CSS approach, we need to render 100 avatars in storybook:
- Avatar - Performance transform
   Render 100 avatars inside one container. Set transform for the container. And use transform to counter rotate every avatar.
- Avatar - Performance left top
   Using absolute position to position every avatar. Use width and height to scale every avatar. Calculate those values (global position and scale) from transform matrix and avatars position (map position) inside map.
- Avatar - Performance left top gpu
   Base on the one without gpu. But calculate values with [gpu acceleration](https://gpu.rocks/#/)

**Comment by hasevr** [comment]
I just change the way to clip the video. The problem was in Chrome, the shape of the video is always 16:9 rectangle and round border can not observe because it is out of square.
I use clip-path then in both FireFox and Chrome it works well.
